services:
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: summarizer

  web:
    image: "ydvankit/video-summarizer"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db:5432/summarizer
    env_file:
      - ./.env
